{
 "title": "HeathCheck Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Service Monitoring",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "netdata_portcheck_status_boolean_average{dimension=\"success\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Service Health Check",
   "type": "stat",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "server_health_check", "legendFormat": "{{serviceName}}" }
   ]
  },
  {
   "title": "Email Service Health Check",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"email\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "User Service Health Check",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"user\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Elasticsearch Service Health Check",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"elasticsearch\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "SMS Service Health Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"sms\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "CMS-Backend Health Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"cms-backend\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Gateway Service Health Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"gateway\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Export Service Health Check",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "server_health_check{serviceName=\"export\"}",
     "legendFormat": "{{serviceName}}"
    }
   ]
  }
 ]
}