apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    orgId: 1
    isDefault: true
    access: proxy
    editable: true
    basicAuth: false
    # basicAuthUser: admin
    # basicAuthPassword: admin
