---
groups:
  - name: SystemPressure
    rules:
      - alert: CpuPressure
        expr: (avg by (instance) (rate(node_pressure_cpu_waiting_seconds_total[1m])) * 100) > 60
        for: 30m
        labels:
          severity: page
        annotations:
          summary: Host CPU pressure (instance {{ $labels.instance }})
          description: "CPU pressure is > 90% for 30m.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: MemoryPressure
        expr: (avg by (instance) (rate(node_pressure_memory_waiting_seconds_total[1m])) * 100) > 60
        for: 30m
        labels:
          severity: page
        annotations:
          summary: Host memory pressure (instance {{ $labels.instance }})
          description: "Memory pressure is > 90% for 30m.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: IOPressure
        expr: (avg by (instance) (rate(node_pressure_io_waiting_seconds_total[1m])) * 100) > 60
        for: 30m
        labels:
          severity: page
        annotations:
          summary: Host IO pressure (instance {{ $labels.instance }})
          description: "IO pressure is > 90% for 30m.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

  - name: SystemMonitoring
    rules:
      - alert: NodeExporterDown
        expr: up{job="node"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Node Exporter is down (instance {{ $labels.instance }})"
          description: "The Node Exporter on server {{ $labels.instance }} is down for more than 1 minute."

      - alert: NodeExporterDiskSpaceLow
        expr: node_filesystem_avail_bytes{fstype=~"ext4|xfs|btrfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs|btrfs"} * 100 < 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter disk space low (instance {{ $labels.instance }})"
          description: "The Node Exporter on server {{ $labels.instance }} has less than 10% disk space left."

      - alert: NodeExporterMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter memory usage high (instance {{ $labels.instance }})"

      - alert: NodeExporterCPUUsage
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter CPU usage high (instance {{ $labels.instance }})"
          description: "The Node Exporter on server {{ $labels.instance }} has more than 90% CPU usage."

      - alert: NodeExporterLoadAverage
        expr: node_load1 > 1
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter load average high (instance {{ $labels.instance }})"
          description: "The Node Exporter on server {{ $labels.instance }} has more than 1 load average."

      - alert: NodeExporterDiskIO
        expr: (rate(node_disk_io_time_seconds_total[1m]) * 1000) > 10
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter disk IO high (instance {{ $labels.instance }})"
          description: "The Node Exporter on server {{ $labels.instance }} has more than 10 disk IO."

      - alert: NodeExporterNetworkTraffic
        expr: (rate(node_network_receive_bytes_total[1m]) + rate(node_network_transmit_bytes_total[1m])) / 1024 / 1024 > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Node Exporter network traffic high (instance {{ $labels.instance }})"
          description: "The Node Exporter on server {{ $labels.instance }} has more than 100 MB network traffic."
