{
 "title": "Docker System Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "label_values(alias)" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Containers Observed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name != \"\"})"
    }
   ]
  },
  {
   "title": "Containers Running (Last 30s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name != \"\"})"
    }
   ]
  },
  {
   "title": "CPU Usage (Last 30s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name != \"\"}[5m]))/sum(machine_cpu_cores))*100"
    }
   ]
  },
  {
   "title": "Memory Usage (Last 30s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(container_memory_usage_bytes{name = \"\"}/1024/1024) /  sum(machine_memory_bytes/1024/1024 )) * 100"
    }
   ]
  },
  {
   "title": "Filesystem Usage (Last 30s)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(SUM(container_fs_usage_bytes/1024/1024/1024)/SUM(container_fs_limit_bytes/1024/1024/1024))*100"
    }
   ]
  },
  {
   "title": "Average Container Lifespan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(container_last_seen{name != \"\"}) - avg(container_start_time_seconds{name != \"\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total{name != \"\"}[5m]))",
     "legendFormat": "Kernel"
    },
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{name != \"\"}[5m])) ",
     "legendFormat": "User"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name != \"\"}[5m])) - sum(rate(container_cpu_system_seconds_total{name != \"\"}[5m])) - sum(rate(container_cpu_user_seconds_total{name != \"\"}[5m])) ",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CPU Usage by Container (Top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_cpu_usage_seconds_total{name != \"\"}[5m]))",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{name = \"\"}/1048576)",
     "legendFormat": "Hot"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name = \"\"}/1048576)",
     "legendFormat": "Total (Hot & Cold)"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{name = \"\"}/1048576)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Memory Usage by Container (Top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,container_memory_usage_bytes{name !=\"\"} / 1024 / 1024)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_reads_total[15m])",
     "legendFormat": "{{ device }} Reads"
    },
    {
     "expr": "rate(container_fs_writes_total[15m])",
     "legendFormat": "{{ device }} Writes"
    }
   ]
  },
  {
   "title": "Filesystem Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Sectors" }
   ],
   "targets": [
    {
     "expr": "rate(container_fs_sector_reads_total[15m])",
     "legendFormat": "{{ device }} Sectors Read"
    },
    {
     "expr": "rate(container_fs_sector_writes_total[15m])",
     "legendFormat": "{{ device }} Sectors Written"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent", "label": "Percent used" }
   ],
   "targets": [
    {
     "expr": "(container_fs_usage_bytes / container_fs_limit_bytes) * 100",
     "legendFormat": "{{ alias }}: {{ device }}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total {name = \"\"}[5m])) ",
     "legendFormat": "Tx bytes"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total {name = \"\"}[5m]))",
     "legendFormat": "Rx bytes"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_errors_total {name != \"\"}[5m]))",
     "legendFormat": "Tx"
    },
    {
     "expr": "sum(rate(container_network_receive_errors_total {name != \"\"}[5m]))",
     "legendFormat": "Rx"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Bytes (Tx) by Container (Top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes per second" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_network_transmit_bytes_total {name != \"\"}[5m]))",
     "legendFormat": "{{name }}"
    }
   ]
  },
  {
   "title": "Bytes (Rx) by Container (Top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes per second" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_network_receive_bytes_total {name != \"\"}[5m]))",
     "legendFormat": "{{name }}"
    }
   ]
  },
  {
   "title": "Errors (Tx) by Container (Top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "Bps", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_network_transmit_errors_total {name != \"\"}[5m]))",
     "legendFormat": "{{name }}"
    }
   ]
  },
  {
   "title": "Errors (Rx) by Container (Top 10)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "Bps", "label": "Errors per second" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate(container_network_receive_errors_total {name != \"\"}[5m]))",
     "legendFormat": "{{name }}"
    }
   ]
  }
 ]
}